### PR TITLE
Use cached config, update/fix CI

### PR DESCRIPTION
**Pull request by bjw-s**
Hi (again, my previous PR got closed because I messed up my fork) 👋

This PR primarily aims to do two things:

Fix the CI (looked to be some kind of issue with the certificate?)
Foltik's version of vyos-go-client currently does an API call each and every time to fetch the current config. My fork (I am intending to raise a PR upstream, but not sure how actively maintained it is) requests the current configuration only once and then keeps that in cache for the duration of the terraform plan/apply.

### CODE REVIEW

**Comment by TGNThump** [comment]
Hey 👋

First of thanks for fixing the CI. I was hitting my head against my desk trying to figure out why it wasn't working... 😅

I'd really appreciate it if you could split the `.ci`, `.vscode` and `.github` changes into their own PR so we can get that merged in first.

On the caching implementation, I have a few concerns about cache invalidation. Currently you're not updating the local copy of the config when the config changes. As a result, the behaviour of a test case like the following would change from erroring and suggesting importing vyos_config.child, to undefined:
```hcl
resource "vyos_config" "parent" {
  path = "service dhcp-server"
  value = jsonencode({
    shared-network-name = {
      TEST = {
        subnet = {
          "10.0.0.0/16" = {
            // ...
          }
        }
      }
    }
  })
}

resource "vyos_config" "child" {
  path = "service dhcp-server shared-network-name TEST"
  value = jsonencode({
    subnet = {
      "10.0.0.0/16" = {
        // ...
      }
    }
  })
  depends_on = [vyos_config.parent]
}
```

**Comment by bjw-s** [comment]
I did indeed notice that the cache wasn't invalidating properly. I do believe I have fixed that in the latest commit(s)?
I will try your testcase locally to see what happens! If I can't sort it out quickly I'll separate the cache feature from the QoL/CI stuff

**Comment by bjw-s** [comment]
Follow-up:

With the following test case:
```hcl
resource "vyos_config" "system-test-parent" {
  path = "system login user test"
  value = jsonencode({
    "authentication": {
      "plaintext-password": "testvalue"
    }
  })
}

resource "vyos_config" "system-test-child" {
  path = "system login user test authentication"
  value = jsonencode({
    "plaintext-password": "newtest"
  })
  depends_on = [
    vyos_config.system-test-parent
  ]
}
```

I now get the following output:

```console
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.config.vyos_config.system-test-child will be created
  + resource "vyos_config" "system-test-child" {
      + id    = (known after apply)
      + path  = "system login user test authentication"
      + value = jsonencode(
            {
              + plaintext-password = "newtest"
            }
        )
    }

  # module.config.vyos_config.system-test-parent will be created
  + resource "vyos_config" "system-test-parent" {
      + id    = (known after apply)
      + path  = "system login user test"
      + value = jsonencode(
            {
              + authentication = {
                  + plaintext-password = "testvalue"
                }
            }
        )
    }

Plan: 2 to add, 0 to change, 0 to destroy.
module.config.vyos_config.system-test-parent: Creating...
module.config.vyos_config.system-test-parent: Still creating... [10s elapsed]
module.config.vyos_config.system-test-parent: Still creating... [20s elapsed]
module.config.vyos_config.system-test-parent: Creation complete after 28s [id=system login user test]
module.config.vyos_config.system-test-child: Creating...
╷
│ Error: Configuration path 'system login user test authentication' already exists, try a resource import instead.
│
│   with module.config.vyos_config.system-test-child,
│   on modules/config/system.tf line 38, in resource "vyos_config" "system-test-child":
│   38: resource "vyos_config" "system-test-child" {
```

I believe that covers your test case? (I couldn't get the DHCP example to work without adding many other fields)

**Comment by bjw-s** [comment]
I think this PR should be about done as-is. Please let me know if you'd like to see anything changed :)

**Comment by bjw-s** [comment]
@TGNThump Sorry for yet another bump, but it's been almost three weeks without a response. 
Just wanted to check in to see if you are planning on merging this? If not, that's cool too but then I'll go ahead and publish my own fork so that I can use these changes without setting a local development override.

**Comment by TGNThump** [comment]
@bjw-s my bad, I misunderstood how review comments worked in GitHub and left them on pending by mistake.

**Review by TGNThump — APPROVED** [review]

**Comment by bjw-s** [comment]
> @bjw-s my bad, I misunderstood how review comments worked in GitHub and left them on pending by mistake.
No worries! That's why I wanted to quickly check in with you first :) 

I see now that I left a comment in, I'll create another PR in a bit to remove that.

**Pull request merged**
